export const errorQuotes = [
	'"I do not fear computers. I fear lack of them." — Isaac Asimov',
	'"A computer once beat me at chess, but it was no match for me at kick boxing." — Emo Philips',
	'"Computer Science is no more about computers than astronomy is about telescopes." — Edsger W. Dijkstra',
	'"Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases." — Norman Augustine',
	'"Physics is the universe’s operating system." — Steven R Garman',
	'"It’s hardware that makes a machine fast.  It’s software that makes a fast machine slow."',
	'"Imagination is more important than knowledge.  For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution." — Albert Einstein',
	'"The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge." — Stephen Hawking',
	'"The more you know, the more you realize you know nothing." — Socrates',
	'"Tell me and I forget.  Teach me and I remember.  Involve me and I learn." — Benjamin Franklin',
	'"Real knowledge is to know the extent of one’s ignorance." — Confucius',
	'"If people never did silly things, nothing intelligent would ever get done." — Ludwig Wittgenstein',
	'"Getting information off the Internet is like taking a drink from a fire hydrant." — Mitchell Kapor',
	'"If you think your users are idiots, only idiots will use it." — Linus Torvalds',
	'"From a programmer’s point of view, the user is a peripheral that types when you issue a read request." — P. Williams',
	'"Where is the ‘any’ key?" — Homer Simpson, in response to the message, "Press any key"',
	'"Computers are good at following instructions, but not at reading your mind." — Donald Knuth',
	'"There is only one problem with common sense; it’s not very common." — Milt Bryce',
	'"The Internet?  We are not interested in it." — Bill Gates, 1993',
	'"The best way to get accurate information on Usenet is to post something wrong and wait for corrections." — Matthew Austern',
	'"Programs must be written for people to read, and only incidentally for machines to execute." — Abelson and Sussman',
	'"Commenting your code is like cleaning your bathroom — you never want to do it, but it really does create a more pleasant experience for you and your guests." — Ryan Campbell',
	'"We have to stop optimizing for programmers and start optimizing for users." — Jeff Atwood',
	'"If we wish to count lines of code, we should not regard them as ‘lines produced’ but as ‘lines spent." — Edsger Dijkstra',
	'"If you automate a mess, you get an automated mess." — Rod Michael',
	'"Looking at code you wrote more than two weeks ago is like looking at code you are seeing for the first time." — Dan Hurvitz',
	'"Code generation, like drinking alcohol, is good in moderation." — Alex Lowe',
	'“Simplicity, carried to the extreme, becomes elegance." — Jon Franklin',
	'"A program is never less than 90% complete, and never more than 95% complete." — Terry Baker',
	'"When you are stuck in a traffic jam with a Porsche, all you do is burn more gas in idle.  Scalability is about building wider roads, not about building faster cars." — Steve Swartz',
	'"Today, most software exists, not to solve a problem, but to interface with other software." — IO Angell',
	'"The difference between theory and practice is that in theory, there is no difference between theory and practice." — Richard Moore',
	'"Don’t document the problem, fix it." — Atli Björgvin Oddsson',
	'"I think it’s a new feature.  Don’t tell anyone it was an accident." — Larry Wall',
	'"If you don’t handle [exceptions], we shut your application down.  That dramatically increases the reliability of the system." — Anders Hejlsberg',
	'"When debugging, novices insert corrective code; experts remove defective code." — Richard Pattis',
	'"There are only two things wrong with C++:  The initial concept and the implementation." — Bertrand Meyer',
	'"BASIC is to computer programming as QWERTY is to typing." — Seymour Papert',
	'"Some people, when confronted with a problem, think ‘I know, I’ll use regular expressions.  Now they have two problems." — Jamie Zawinski',
	'"Before man reaches the moon, mail will be delivered within hours from New York to California, to Britain, to India or Australia." — Arthur Summerfield, 1959, United States Post'
];